### ISSUE TITLE
Error with 2.2.0 Error: Input does not meet YAML 1.2 "Core Schema" specification: setup

### ISSUE THREAD

**Issue by DavidMc2021** [Souvikns/Notion-Board#59]
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/87083141/161146871-08bef389-30b9-4d5e-93a7-d5b5997f3816.png">

**Comment by Souvikns** [comment]
@DavidMc2021 did you update the workflow file it has changed from before. 

```yaml
name: Notion Board
on:
  issues:
  issue_comment:
  workflow_dispatch:
    inputs:
      setup:
        description: 'Populate your notion database with all the requried properties'
        type: boolean
      syncIssues:
        description: 'sync all other existing issues in this repo'
        type: boolean
      issueType:
        type: choice
        description: 'The issue type you want to sync'
        options:
          - all
          - open
          - closed
        default: open
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Board
        uses: Souvikns/Notion-Board@2.2.0
        with:
          setup: ${{github.event.inputs.setup}}
          syncIssues: ${{github.event.inputs.syncIssues}}
          issueType: ${{github.event.inputs.issueType}}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
          
```
